<!doctype html>
<html>
<head><meta charset="utf-8"><title>Cashflow</title></head>
<body>
    <h2>Cashflow</h2>
    <p>Period: {{ $from }} to {{ $to }}</p>
    <table border="1" cellpadding="6" cellspacing="0">
        <tr><th>Metric</th><th>Amount</th></tr>
        <tr><td>Inflows</td><td>{{ number_format($data['inflows'], 2) }}</td></tr>
        <tr><td>Outflows</td><td>{{ number_format($data['outflows'], 2) }}</td></tr>
        <tr><td><strong>Net Cash</strong></td><td><strong>{{ number_format($data['net_cash'], 2) }}</strong></td></tr>
    </table>
    <p style="font-size: 11px; margin-top: 12px;">Generated by TaxPilot</p>
</body>
</html>

