<!doctype html>
<html>
<head><meta charset="utf-8"><title>P&amp;L</title></head>
<body>
    <h2>Profit &amp; Loss</h2>
    <p>Period: {{ $from }} to {{ $to }}</p>
    <table border="1" cellpadding="6" cellspacing="0">
        <tr><th>Metric</th><th>Amount</th></tr>
        <tr><td>Income</td><td>{{ number_format($data['income'], 2) }}</td></tr>
        <tr><td>Expenses</td><td>{{ number_format($data['expenses'], 2) }}</td></tr>
        <tr><td><strong>Net</strong></td><td><strong>{{ number_format($data['net'], 2) }}</strong></td></tr>
    </table>
    <p style="font-size: 11px; margin-top: 12px;">Generated by TaxPilot</p>
    </body>
</html>

