<!doctype html>
<html>
<head><meta charset="utf-8"><title>Trial Balance</title></head>
<body>
    <h2>Trial Balance</h2>
    <p>Period: {{ $from }} to {{ $to }}</p>
    <table border="1" cellpadding="6" cellspacing="0">
        <tr><th>Code</th><th>Name</th><th>Debit</th><th>Credit</th></tr>
        @foreach($lines as $l)
            <tr>
                <td>{{ $l->code }}</td>
                <td>{{ $l->name }}</td>
                <td>{{ number_format((float)$l->debit, 2) }}</td>
                <td>{{ number_format((float)$l->credit, 2) }}</td>
            </tr>
        @endforeach
    </table>
    <p style="font-size: 11px; margin-top: 12px;">Generated by TaxPilot</p>
</body>
</html>

