<!doctype html>
<html>
<head><meta charset="utf-8"><title>CIT Filing Pack</title></head>
<body>
    <h2>CIT Filing Pack</h2>
    <p>Transaction ID: {{ $tx->id }}</p>
    <h3>Summary</h3>
    <table border="1" cellpadding="6" cellspacing="0">
        <tr><td>Profit before adjustment</td><td>{{ number_format($s['amounts']['profit_before_adjustment'] ?? 0, 2) }}</td></tr>
        <tr><td>Adjustments</td><td>{{ number_format($s['amounts']['adjustments'] ?? 0, 2) }}</td></tr>
        <tr><td>Loss relief applied</td><td>{{ number_format($s['amounts']['loss_relief_applied'] ?? 0, 2) }}</td></tr>
        <tr><td>Taxable profit</td><td>{{ number_format($s['amounts']['taxable_profit'] ?? 0, 2) }}</td></tr>
        <tr><td>Calculated tax</td><td>{{ number_format($s['amounts']['calculated_tax'] ?? 0, 2) }}</td></tr>
        <tr><td>Minimum tax</td><td>{{ number_format($s['amounts']['minimum_tax'] ?? 0, 2) }}</td></tr>
        <tr><td><strong>Tax payable</strong></td><td><strong>{{ number_format($s['amounts']['tax_payable'] ?? 0, 2) }}</strong></td></tr>
    </table>
    <p style="font-size: 11px; margin-top: 12px;">Generated by TaxPilot</p>
</body>
</html>

