<!doctype html>
<html>
<head><meta charset="utf-8"><title>PIT Filing Pack</title></head>
<body>
    <h2>PIT Filing Pack</h2>
    <p>Transaction ID: {{ $tx->id }}</p>
    <h3>Summary</h3>
    <table border="1" cellpadding="6" cellspacing="0">
        <tr><td>Gross income</td><td>{{ number_format($s['amounts']['gross_income'] ?? 0, 2) }}</td></tr>
        <tr><td>Taxable income</td><td>{{ number_format($s['amounts']['taxable_income'] ?? 0, 2) }}</td></tr>
        <tr><td>Country tax</td><td>{{ number_format($s['amounts']['country_tax'] ?? 0, 2) }}</td></tr>
        <tr><td>State tax</td><td>{{ number_format($s['amounts']['state_tax'] ?? 0, 2) }}</td></tr>
        <tr><td>Local tax</td><td>{{ number_format($s['amounts']['local_tax'] ?? 0, 2) }}</td></tr>
        <tr><td><strong>Total tax</strong></td><td><strong>{{ number_format($s['amounts']['total_tax'] ?? 0, 2) }}</td></strong></tr>
        <tr><td><strong>Net tax due</strong></td><td><strong>{{ number_format($s['amounts']['net_tax_due'] ?? 0, 2) }}</strong></td></tr>
    </table>
    <p style="font-size: 11px; margin-top: 12px;">Generated by TaxPilot</p>
</body>
</html>

